CRUD/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('book.urls', namespace='book')),
]

book/urls.py
from django.urls import path
from book import views

app_name = 'book'

urlpatterns = [
  path('', views.book_list, name='book_list'),
  path('new', views.book_create, name='book_new'),
  path('edit/<int:pk>', views.book_update, name='book_edit'),
  path('delete/<int:pk>', views.book_delete, name='book_delete'),
]

book/models.py
import datetime
from django.db import models

# Create your models here.
class Book(models.Model):
    book_choices = (
        ('one of novel','One of Novel'),
        ('documentation','Documentation'),
        ('other','Other'),
    )

    title = models.CharField(max_length=100)
    author = models.CharField(max_length=100)
    date_published = models.DateField(default=datetime.datetime.today, blank=True, null=True)
    number_of_page = models.IntegerField(blank=True, null=True)
    type_of_book = models.CharField(blank=True, max_length=100, choices=book_choices)

    def __str__(self):
        return self.title

book/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.forms import ModelForm

from book.models import Book
# Create your views here.

class BookForm(ModelForm):
    class Meta:
        model = Book
        fields = ['title', 'author', 'date_published', 'number_of_page', 'type_of_book']

def book_list(request, template_name='book_list.html'):
    book = Book.objects.all()
    data = {}
    data['object_list'] = book
    return render(request, template_name, data)

def book_create(request, template_name='book_form.html'):
    form = BookForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('book:book_list')
    return render(request, template_name, {'form':form})

def book_update(request, pk, template_name='book_edit.html'):
    book= get_object_or_404(Book, pk=pk)
    form = BookForm(request.POST or None, instance=book)
    if form.is_valid():
        form.save()
        return redirect('book:book_list')
    return render(request, template_name, {'form':form})

def book_delete(request, pk, template_name='book_confirm_delete.html'):
    book= get_object_or_404(Book, pk=pk)
    if request.method=='POST':
        book.delete()
        return redirect('book:book_list')
    return render(request, template_name, {'object':book})

book/templates/book_confirm_delete.html
{% extends "base.html" %}

{% block content %}

<h2><a href="{% url 'book:book_list' %}">Book</a>: Delete?</h2>

<form method="post">{% csrf_token %}
    Are you sure you want to delete "{{ object }}" ?<br/>
    <input type="submit" value="Delete" />
</form>

{% endblock %}

book/templates/book_edit.html
{% extends "base.html" %}

{% block content %}

<h2><a href="{% url 'book:book_list' %}">Book</a>: Edit</h2>

<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" />
</form>

{% endblock %}

book/templates/book_form.html
{% extends "base.html" %}

{% block content %}

<h2><a href="{% url 'book:book_list' %}">Book</a>: New</h2>

<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" />
</form>

{% endblock %}

book/templates/book_list.html
{% extends "base.html" %}

{% block content %}

<h2><a href="{% url 'book:book_list' %}">Book</a></h2>

<table class="table">
    <tr>
        <th>Title</th>
        <th>Author</th>
        <th>Date Published</th>
        <th>Number_of Page</th>
        <th>Type of Book</th>
        <th>Action</th>
    </tr>
{% for book in object_list %}
    <tr>
        <td>{{book.title}}</td>
        <td>{{book.author}}</td>
        <td>{{book.date_published}}</td>
        <td>{{book.number_of_page}}</td>
        <td>{{book.type_of_book}}</td>
        <td>
          <a href="{% url 'book:book_edit' book.id %}">edit</a>
          <a href="{% url 'book:book_delete' book.id %}">delete</a>
        </td>
    </tr>
{% endfor %}
</table>

<a href="{% url 'book:book_new' %}">New</a>

{% endblock %}

templates/base.html
{% load static %}

<html>
<head>
    <title>Book</title>
    <link href="/static/vendors/sb-admin/bower_components/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/vendors/sb-admin/dist/css/sb-admin-2.css" rel="stylesheet">
</head>
<body>
    <div id="header">
        <h1><a href="/">Django CRUD Book</a></h1>
    </div><!-- header -->
    <div id="content">
        {% block content %}
        {% endblock %}
    </div><!-- content -->
</body>
</html>